/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String welcome() {
        return "Super Duper!!!";
    }

    public String welcomeHome() {
        return "Welcome Home!!!";
    }

    public String featureSuper() {
        return "Super Feature!!";
    }

    public String featureSuper2() {
        return "Super Feature2!!";
    }
}
